# Generated by Django 4.1.2 on 2022-10-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilatec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
