# Generated by Django 4.1.2 on 2022-10-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alquilatec', '0002_equipo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='equipos',
        ),
        migrations.CreateModel(
            name='EquipoAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilatec.alquiler')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilatec.equipo')),
            ],
        ),
    ]
